{
 Bieu thuc chia la bieu thuc co dang x1/x2/x3/.../xn
nguoi ta tinh gia tri bieu thuc bang cach thuc hien lan luot cac phep chia tu
trai sang phai
 Vd: 1/2/1/2=1/4
Tuy nhien chung ta co the them vao bieu thuc cac dau ngoac de thay doi gia tri
cua bieu thuc.
 Vd:(1/2)/(1/2)=1
Hay viet chuong trinh kiem tra xem co the them cac dau ngoac vao 1 bieu thuc
chia de cho gia tri cua no la 1 so nguyen hay khong?

Du lieu vao lay tu tap tin DIV.INP co cau truc:
- Dong dau la so n(2<n<=10000)
- Dong thu i trong n dong tiep theo ghi so xi(0<xi<10^9) cua bieu thuc chia
Du lieu ra la tap tin DIV.OUT co cau truc:
- Dong dau ghi YES neu co cach them cac dau ngoac hoac ghi NO
- Neu co cach them dau ngoac thi cac dong tiep theo ghi tat ca cac cach them.
}