#include <iostream.h>
#include <conio.h>
main()
{
 clrscr();
 cout<<"\t\t50 so chan.";
 cout<<"\n\tBat dau tu 2.\n";
 for (int i=1;i<=50;i++) cout<<i*2<<" ";
 cout<<"\n\tBat dau tu 10.\n";
 for (i=5;i<=55;i++) cout<<i*2<<" ";
 cout<<"\n\t50 so le.\n";
 cout<<"\tBat dau tu 1.\n";
 for (i=1;i<=50;i++) cout<<i*2-1<<" ";
 cout<<"\n\tBat dau tu 57.\n";
 for (i=29;i<=50+29;i++) cout<<i*2-1<<" ";
 return 0;
}