//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1434.
// 
#pragma warning disable 1591

namespace QLTV.BUS_WS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BUS_ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class BUS_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoaiDocGia_GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoaiDocGia_GetByPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TheDocGia_GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback TheDocGia_GetByPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TheDocGia_InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback TheDocGia_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TheDocGia_DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BUS_Service() {
            this.Url = global::QLTV.Properties.Settings.Default.QLTV_BUS_WS_BUS_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoaiDocGia_GetAllCompletedEventHandler LoaiDocGia_GetAllCompleted;
        
        /// <remarks/>
        public event LoaiDocGia_GetByPropertiesCompletedEventHandler LoaiDocGia_GetByPropertiesCompleted;
        
        /// <remarks/>
        public event TheDocGia_GetAllCompletedEventHandler TheDocGia_GetAllCompleted;
        
        /// <remarks/>
        public event TheDocGia_GetByPropertiesCompletedEventHandler TheDocGia_GetByPropertiesCompleted;
        
        /// <remarks/>
        public event TheDocGia_InsertCompletedEventHandler TheDocGia_InsertCompleted;
        
        /// <remarks/>
        public event TheDocGia_UpdateCompletedEventHandler TheDocGia_UpdateCompleted;
        
        /// <remarks/>
        public event TheDocGia_DeleteCompletedEventHandler TheDocGia_DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoaiDocGia_GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoaiDocGiaDTO[] LoaiDocGia_GetAll() {
            object[] results = this.Invoke("LoaiDocGia_GetAll", new object[0]);
            return ((LoaiDocGiaDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LoaiDocGia_GetAllAsync() {
            this.LoaiDocGia_GetAllAsync(null);
        }
        
        /// <remarks/>
        public void LoaiDocGia_GetAllAsync(object userState) {
            if ((this.LoaiDocGia_GetAllOperationCompleted == null)) {
                this.LoaiDocGia_GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoaiDocGia_GetAllOperationCompleted);
            }
            this.InvokeAsync("LoaiDocGia_GetAll", new object[0], this.LoaiDocGia_GetAllOperationCompleted, userState);
        }
        
        private void OnLoaiDocGia_GetAllOperationCompleted(object arg) {
            if ((this.LoaiDocGia_GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoaiDocGia_GetAllCompleted(this, new LoaiDocGia_GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoaiDocGia_GetByProperties", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoaiDocGiaDTO[] LoaiDocGia_GetByProperties(string[] lstKey, object[] Values, bool[] Exact) {
            object[] results = this.Invoke("LoaiDocGia_GetByProperties", new object[] {
                        lstKey,
                        Values,
                        Exact});
            return ((LoaiDocGiaDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void LoaiDocGia_GetByPropertiesAsync(string[] lstKey, object[] Values, bool[] Exact) {
            this.LoaiDocGia_GetByPropertiesAsync(lstKey, Values, Exact, null);
        }
        
        /// <remarks/>
        public void LoaiDocGia_GetByPropertiesAsync(string[] lstKey, object[] Values, bool[] Exact, object userState) {
            if ((this.LoaiDocGia_GetByPropertiesOperationCompleted == null)) {
                this.LoaiDocGia_GetByPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoaiDocGia_GetByPropertiesOperationCompleted);
            }
            this.InvokeAsync("LoaiDocGia_GetByProperties", new object[] {
                        lstKey,
                        Values,
                        Exact}, this.LoaiDocGia_GetByPropertiesOperationCompleted, userState);
        }
        
        private void OnLoaiDocGia_GetByPropertiesOperationCompleted(object arg) {
            if ((this.LoaiDocGia_GetByPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoaiDocGia_GetByPropertiesCompleted(this, new LoaiDocGia_GetByPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TheDocGia_GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TheDocGiaDTO[] TheDocGia_GetAll() {
            object[] results = this.Invoke("TheDocGia_GetAll", new object[0]);
            return ((TheDocGiaDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void TheDocGia_GetAllAsync() {
            this.TheDocGia_GetAllAsync(null);
        }
        
        /// <remarks/>
        public void TheDocGia_GetAllAsync(object userState) {
            if ((this.TheDocGia_GetAllOperationCompleted == null)) {
                this.TheDocGia_GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTheDocGia_GetAllOperationCompleted);
            }
            this.InvokeAsync("TheDocGia_GetAll", new object[0], this.TheDocGia_GetAllOperationCompleted, userState);
        }
        
        private void OnTheDocGia_GetAllOperationCompleted(object arg) {
            if ((this.TheDocGia_GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TheDocGia_GetAllCompleted(this, new TheDocGia_GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TheDocGia_GetByProperties", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TheDocGiaDTO[] TheDocGia_GetByProperties(string[] lstKey, object[] Values, bool[] Exact) {
            object[] results = this.Invoke("TheDocGia_GetByProperties", new object[] {
                        lstKey,
                        Values,
                        Exact});
            return ((TheDocGiaDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void TheDocGia_GetByPropertiesAsync(string[] lstKey, object[] Values, bool[] Exact) {
            this.TheDocGia_GetByPropertiesAsync(lstKey, Values, Exact, null);
        }
        
        /// <remarks/>
        public void TheDocGia_GetByPropertiesAsync(string[] lstKey, object[] Values, bool[] Exact, object userState) {
            if ((this.TheDocGia_GetByPropertiesOperationCompleted == null)) {
                this.TheDocGia_GetByPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTheDocGia_GetByPropertiesOperationCompleted);
            }
            this.InvokeAsync("TheDocGia_GetByProperties", new object[] {
                        lstKey,
                        Values,
                        Exact}, this.TheDocGia_GetByPropertiesOperationCompleted, userState);
        }
        
        private void OnTheDocGia_GetByPropertiesOperationCompleted(object arg) {
            if ((this.TheDocGia_GetByPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TheDocGia_GetByPropertiesCompleted(this, new TheDocGia_GetByPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TheDocGia_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TheDocGia_Insert(ref TheDocGiaDTO dto) {
            object[] results = this.Invoke("TheDocGia_Insert", new object[] {
                        dto});
            dto = ((TheDocGiaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void TheDocGia_InsertAsync(TheDocGiaDTO dto) {
            this.TheDocGia_InsertAsync(dto, null);
        }
        
        /// <remarks/>
        public void TheDocGia_InsertAsync(TheDocGiaDTO dto, object userState) {
            if ((this.TheDocGia_InsertOperationCompleted == null)) {
                this.TheDocGia_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTheDocGia_InsertOperationCompleted);
            }
            this.InvokeAsync("TheDocGia_Insert", new object[] {
                        dto}, this.TheDocGia_InsertOperationCompleted, userState);
        }
        
        private void OnTheDocGia_InsertOperationCompleted(object arg) {
            if ((this.TheDocGia_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TheDocGia_InsertCompleted(this, new TheDocGia_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TheDocGia_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TheDocGia_Update(TheDocGiaDTO dto) {
            this.Invoke("TheDocGia_Update", new object[] {
                        dto});
        }
        
        /// <remarks/>
        public void TheDocGia_UpdateAsync(TheDocGiaDTO dto) {
            this.TheDocGia_UpdateAsync(dto, null);
        }
        
        /// <remarks/>
        public void TheDocGia_UpdateAsync(TheDocGiaDTO dto, object userState) {
            if ((this.TheDocGia_UpdateOperationCompleted == null)) {
                this.TheDocGia_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTheDocGia_UpdateOperationCompleted);
            }
            this.InvokeAsync("TheDocGia_Update", new object[] {
                        dto}, this.TheDocGia_UpdateOperationCompleted, userState);
        }
        
        private void OnTheDocGia_UpdateOperationCompleted(object arg) {
            if ((this.TheDocGia_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TheDocGia_UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TheDocGia_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TheDocGia_Delete(TheDocGiaDTO dto) {
            this.Invoke("TheDocGia_Delete", new object[] {
                        dto});
        }
        
        /// <remarks/>
        public void TheDocGia_DeleteAsync(TheDocGiaDTO dto) {
            this.TheDocGia_DeleteAsync(dto, null);
        }
        
        /// <remarks/>
        public void TheDocGia_DeleteAsync(TheDocGiaDTO dto, object userState) {
            if ((this.TheDocGia_DeleteOperationCompleted == null)) {
                this.TheDocGia_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTheDocGia_DeleteOperationCompleted);
            }
            this.InvokeAsync("TheDocGia_Delete", new object[] {
                        dto}, this.TheDocGia_DeleteOperationCompleted, userState);
        }
        
        private void OnTheDocGia_DeleteOperationCompleted(object arg) {
            if ((this.TheDocGia_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TheDocGia_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoaiDocGiaDTO {
        
        private int maLoaiDocGiaField;
        
        private string tenLoaiDocGiaField;
        
        /// <remarks/>
        public int MaLoaiDocGia {
            get {
                return this.maLoaiDocGiaField;
            }
            set {
                this.maLoaiDocGiaField = value;
            }
        }
        
        /// <remarks/>
        public string TenLoaiDocGia {
            get {
                return this.tenLoaiDocGiaField;
            }
            set {
                this.tenLoaiDocGiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1434")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TheDocGiaDTO {
        
        private int maTheField;
        
        private string hoTenField;
        
        private string diaChiField;
        
        private string emailField;
        
        private System.DateTime ngaySinhField;
        
        private System.DateTime ngayLapTheField;
        
        private System.DateTime ngayHetHanField;
        
        private LoaiDocGiaDTO loaiDocGiaField;
        
        /// <remarks/>
        public int MaThe {
            get {
                return this.maTheField;
            }
            set {
                this.maTheField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayLapThe {
            get {
                return this.ngayLapTheField;
            }
            set {
                this.ngayLapTheField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayHetHan {
            get {
                return this.ngayHetHanField;
            }
            set {
                this.ngayHetHanField = value;
            }
        }
        
        /// <remarks/>
        public LoaiDocGiaDTO LoaiDocGia {
            get {
                return this.loaiDocGiaField;
            }
            set {
                this.loaiDocGiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void LoaiDocGia_GetAllCompletedEventHandler(object sender, LoaiDocGia_GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoaiDocGia_GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoaiDocGia_GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoaiDocGiaDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoaiDocGiaDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void LoaiDocGia_GetByPropertiesCompletedEventHandler(object sender, LoaiDocGia_GetByPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoaiDocGia_GetByPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoaiDocGia_GetByPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoaiDocGiaDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoaiDocGiaDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void TheDocGia_GetAllCompletedEventHandler(object sender, TheDocGia_GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TheDocGia_GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TheDocGia_GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TheDocGiaDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TheDocGiaDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void TheDocGia_GetByPropertiesCompletedEventHandler(object sender, TheDocGia_GetByPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TheDocGia_GetByPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TheDocGia_GetByPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TheDocGiaDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TheDocGiaDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void TheDocGia_InsertCompletedEventHandler(object sender, TheDocGia_InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TheDocGia_InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TheDocGia_InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TheDocGiaDTO dto {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TheDocGiaDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void TheDocGia_UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void TheDocGia_DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591